### PR TITLE
UtsavAH

### PR DESCRIPTION
**Pull request by kishorsharma77**
UtsavAH

### CODE REVIEW

**Review by karthikraman — CHANGES_REQUESTED** [review]
Looks great. manvAdi should not be vaiShNava? All other renames OK.

**Comment by vvasuki** [comment]
> Looks great. manvAdi should not be vaiShNava? All other renames OK.

@kishorsharma77 तथा विदधातु।

**Comment by kishorsharma77** [comment]
> Looks great. manvAdi should not be vaiShNava? All other renames OK.

yes. Placed as earlier

**Comment by kishorsharma77** [comment]
> > Looks great. manvAdi should not be vaiShNava? All other renames OK.
> 
> @kishorsharma77 तथा विदधातु।

विहितम्

**Pull request merged**
